name: Setup
description: Sets up python and poetry

# note:
# this is a local composite action
# documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# code example: https://github.com/GuillaumeFalourd/poc-github-actions/blob/main/.github/actions/local-action/action.yaml

runs:
  using: "composite"
  steps:
    - name: Avoid git conflicts when tag and branch pushed at same time
      if: startsWith(github.ref, 'refs/tags')
      run: sleep 60
      shell: bash

    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"

    - name: Install project dependencies
      run: |
        poetry env use python3.10
        poetry about
        poetry install --with dev
      shell: bash
