name: Release-Docs

on:
  push:
    branches:
      - master
      - main
      - docs
      - lint
      - lint-ci
    tags:
      - "*"

jobs:
  development:
    uses: ./.github/workflows/development.yml

  release-docs:
    runs-on: ubuntu-latest
    needs: development
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Build docs
        run: make docs

      - name: Move docs to versioned directory
        run: |
          mkdir -p .github/pages/
          mv docs/build/html ".github/pages/${GITHUB_REF##*/}"
          ls -la .github/pages
          echo ".github/pages/${GITHUB_REF##*/}"
          ls -la ".github/pages/${GITHUB_REF##*/}"

      - name: Write versions.txt
        run: poetry run sphinx_rtd_theme_github_versions .github/pages

      - name: Publish Docs to gh-pages
        if: github.event_name == 'push'
        # We pin to the github action's SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 # v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true
